// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGuBpQcTzf4l6JPLZOB3-z_j0oBJuPL90',
    appId: '1:1086805966800:web:6d4e1cb7595c1b573903d5',
    messagingSenderId: '1086805966800',
    projectId: 'chatnine-1f56c',
    authDomain: 'chatnine-1f56c.firebaseapp.com',
    storageBucket: 'chatnine-1f56c.firebasestorage.app',
    measurementId: 'G-FT2KJ5ZB2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGzXl5sHxaR3hxticTVW6_lv9xftZywYw',
    appId: '1:1086805966800:android:33aa36645950be0d3903d5',
    messagingSenderId: '1086805966800',
    projectId: 'chatnine-1f56c',
    storageBucket: 'chatnine-1f56c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNzrQgmBT_W6x3jahp41-zd5Zf5V_UKhY',
    appId: '1:1086805966800:ios:4a06453cb1c504643903d5',
    messagingSenderId: '1086805966800',
    projectId: 'chatnine-1f56c',
    storageBucket: 'chatnine-1f56c.firebasestorage.app',
    iosBundleId: 'com.example.chatnine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNzrQgmBT_W6x3jahp41-zd5Zf5V_UKhY',
    appId: '1:1086805966800:ios:4a06453cb1c504643903d5',
    messagingSenderId: '1086805966800',
    projectId: 'chatnine-1f56c',
    storageBucket: 'chatnine-1f56c.firebasestorage.app',
    iosBundleId: 'com.example.chatnine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGuBpQcTzf4l6JPLZOB3-z_j0oBJuPL90',
    appId: '1:1086805966800:web:aaefc597690a99203903d5',
    messagingSenderId: '1086805966800',
    projectId: 'chatnine-1f56c',
    authDomain: 'chatnine-1f56c.firebaseapp.com',
    storageBucket: 'chatnine-1f56c.firebasestorage.app',
    measurementId: 'G-K2BGG1SN7L',
  );

}
