name: chatnine
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^4.15.6
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.8.4
  firebase_analytics: ^10.10.4
  cupertino_icons: ^1.0.8
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.4.0
  image_picker: ^0.8.6+1
  url_launcher: ^6.2.5
  flutter_webrtc: ^0.12.11
  provider: ^6.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  web: ^0.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"